name: DeathTpPlus
main: com.lonelydime.DeathTpPlus.DeathTpPlus
version: 1.86
website: https://github.com/lonelydime
author: lonelydime
description: >
             Death commands including deathtp, deathnotify and deathstreaks.

commands:
  deathtp:
    description: Teleports you back to your last death location
    usage: |
           /<command>
  streak:
    description: Lets you view your or other's kill/death streak.
    usage: |
           /<command> [player]
           Example: /<command> - Displays your streak.
           Example: /<command> lonelydime's - checks lonelydime's streak.
  deaths:
    description: Lets you view your or other's total deaths.
    usage: |
           /<command> (username) (cause)
           Example: /<command> - Displays your total death count.
           Example: /<command> lonelydime - Displays total death count.
           Example: /<command> lonelydime creeper - checks lonelydime's deaths by creeper.
  kills:
    description: Lets you view your or other's total pvp kills.
    usage: |
           /<command> (username) (playername)
           Example: /<command> - Displays your total kill count.
           Example: /<command> lonelydime - Displays total kill count.
           Example: /<command> lonelydime irsmartlikerock - prints times lonelydime killed irsmartlikerock.