name: DeathTpPlus
main: com.lonelydime.DeathTpPlus.DeathTpPlus
version: 1.76
website: https://github.com/lonelydime
author: lonelydime
description: >
             Death commands including deathtp, deathnotify and deathstreaks.

commands:
  deathtp:
    description: Teleports you back to your last death location
    usage: |
           /<command>
  suicide:
    description: Kills yourself.
    usage: |
           /<command>
  streak:
    description: Lets you view your or other's kill/death streak.
    usage: |
           /<command> [player]
           Example: /<command> - Displays your streak.
           Example: /<command> username - checks username's streak.